### ISSUE TITLE
Improve Github documentation

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/docs#247]
#### Summarize the content issue

With the latest improvements for GitHub we 

#### URL(s)

[Provide the URL(s) for the page(s) where the issue exists.](https://mondoo.com/docs/cnspec/saas/github/)

#### What the docs say

- ability to only discovery repos on org
- cover the repo filtering on an organization
- use custom app credentials

#### What the docs SHOULD say

With the released improvements you can start a scan of individual repos where lunalectric is your org and frontend,backend is the list of the repo names we want to scan:

```
cnspec scan github org lunalectric --repos "frontend,backend" --discover repos
```

To include the organization itself, just run:

```
cnspec scan github org lunalectric --repos "frontend,backend"
```

The same can also be achieved by using Mondoo's inventory file:

```yaml
spec:
  assets:
    - connections:
        - type: github
          options:
            organization: lunalectric
            repos: frontend,backend
            repos-exclude: ""
          discover:
            targets:
              - auto
```

With that inventory, you could run the scan:

```shell
cnspec scan --inventory-file github-inventory.yml
```

**Authentication**

Instead of token authentication, we also support the use of custom github application credentials. See https://docs.github.com/en/apps/creating-github-apps. Once the app was created, you can use the app id and the private key to authenticate scans:

```shell
cnquery scan github org mondoohq --app-id 1234 --app-installation-id 123456 --app-private-key <path-to-pem>
```
