### ISSUE TITLE
cloud-init installation doc seems to be wrong

### ISSUE THREAD

**Issue by marcelhuth** [mondoohq/docs#573]
#### Summarize the content issue

In Mondoo docs installation does not work as documented for installing Mondoo via cloud-init.

#### URL(s)

[https://mondoo.com/docs/platform/infra/opsys/automation/cloudinit/](https://mondoo.com/docs/platform/infra/opsys/automation/cloudinit/)

#### What the docs say

```shell
#!/bin/bash
export MONDOO_REGISTRATION_TOKEN='ey..gg'
bash -c "$(curl -sSL https://install.mondoo.com/sh)"
```

#### What the docs SHOULD say

```shell
#!/bin/bash
export MONDOO_REGISTRATION_TOKEN='ey..gg'
curl -sSL https://install.mondoo.com/sh | bash -s -- -u enable -s enable -t $MONDOO_REGISTRATION_TOKEN
```

#### Screenshots

not available

#### References

It looks like in Mondoo installer the variable that would have the exported `$MONDOO_REGISTRATION_TOKEN` value is set to an empty string in the [installer repo](https://github.com/mondoohq/installer/blob/19396c211e701600eab550294b00a2b2bb99c37b/install.sh#L49) in favor of getting the value for the token from the command line via `getopts`. So the token would be always empty and Mondoo cannot register with an empty empty when using the document way.

#### Notes

Probably the same behavior is true in other parts of the documentation where an environment variable is set before running installer with `bash -c ...`.

In my example installations via cloud-init I usually take the following snippet in cloud-init.yml to install Mondoo which works as expected:

```yaml
write_files:
- content: |
    #!/bin/bash
    export MONDOO_REGISTRATION_TOKEN='ey..gg'
    curl -sSL https://install.mondoo.com/sh | bash -s -- -u enable -s enable -t $MONDOO_REGISTRATION_TOKEN
  path: /var/tmp/install_mondoo.sh
  permissions: '0777'

runcmd:
  - /var/tmp/install_mondoo.sh
```

In the Mondoo console the command created for installing Mondoo as a new asset is correctly shown and done the `bash -s`-way.
